### ISSUE TITLE
Tutorial: Missing step in getting started

### ISSUE THREAD

**Issue by petrofcikmatus** [zeit/next-site#101]
There is missing step at https://nextjs.org/learn/basics/getting-started/setup.

I followed every step, but when I run `npm run dev` for the first time, I got none of those 4 available options.

Output from my terminal:
```
petrofcikm@behemoth:~/projects/hello-next$ npm run dev

> hello-next@1.0.0 dev /home/petrofcikm/projects/hello-next
> next

> Couldn't find a `pages` directory. Please create one under the project root
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hello-next@1.0.0 dev: `next`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hello-next@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/petrofcikm/.npm/_logs/2019-01-12T20_12_46_304Z-debug.log
```

I had to create directory `pages` in project root directory to make it work as planned. 

It is simple to fix as output says what to do, but it might be frustrating for new developers as first run of the project does not work out of the box.

**Comment by petrofcikmatus** [comment]
Hi @quietshu, I guess I am blind :man_facepalming: 

Sorry for creating an issue, I really didn't see that.

**Comment by quietshu** [comment]
No worries @petrofcikmatus! 

Feel free to let us know if anything needs improving, or send a PR to https://github.com/zeit/learnnextjs-content.
