### ISSUE TITLE
Unspecific Question "What's the URL of that page?"

### ISSUE THREAD

**Issue by julmot** [zeit/next-site#106]
This question of [this chapter](https://learnnextjs.com/basics/create-dynamic-pages/adding-a-list-of-posts
) has two correct answers:

> What's the URL of that page?

Behind the scenes it's indeed 

> http://localhost:3000/post?title=Hello%20Next.js

However, in the browser it'll look like this:

![urlbar](https://user-images.githubusercontent.com/8310677/35510450-6b07916a-04f8-11e8-9d32-e61678f868a5.png)

So either this answer shouldn't be wrong or the question should be more explicit:

![example](https://user-images.githubusercontent.com/8310677/35510464-76fa2ff0-04f8-11e8-8a35-ffb748beb9e5.png)

**Comment by Tomekmularczyk** [comment]
I think this is related to #35

**Comment by timneutkens** [comment]
Duplicate of #35

**Comment by timneutkens** [comment]
Yep! It's the same issue it seems.
