### ISSUE TITLE
Fetching Data for Pages chapter - two places to improve

### ISSUE THREAD

**Issue by revelt** [zeit/next-site#107]
## 1. Add instructions where to find "server console"

[Fetching Batman Shows](https://learnnextjs.com/basics/fetching-data-for-pages/fetching-batman-shows) instructs:

> Now, have a look at both the browser console and server console.

Sorry but I have no clue how to open "server console". Even Google doesn't give results, try searching for "next server console". It's maybe elementary for somebody but not for peeps like me first time working on server-side apps.

Please elaborate (ideally with visual instructions) _how to open both consoles_. Some students might be not even clear what "browser console" console is, since for them it's usually "the last tab on Chrome Inspect".

Let's add clear instructions how to find both consoles, "server" and "browser".

## 2. Unclear final chapter question

> Now, have a look at both the browser console and server console.
> Then reload the page.
> Where did you see the above message printed after page reload?

Sorry but it is not clear what the "above message" is. Please elaborate. Maybe the original intention was to place some image but it's missing?

---

Other than that, everything up until this page is very clear and easy to follow.

**Comment by kheruc** [comment]
Fixed via #277
