### ISSUE TITLE
Concurrently running commands on Windows

### ISSUE THREAD

**Issue by julmot** [zeit/next-site#111]
https://learnnextjs.com/basics/deploying-a-nextjs-app/run-two-instances

This alone won't make two ports listening on Windows:

![topic](https://user-images.githubusercontent.com/8310677/35515878-97dd19fa-050a-11e8-8896-fad1c1af7460.png)

You'll need something like [concurrently](https://github.com/kimmobrunfeldt/concurrently) and then run e.g. this `$ npm run horizontally` on Windows:

```javascript
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "next",
    "start": "next start -p %PORT%",
    "build": "next build",
    "horizontally": "concurrently \"cross-env PORT=9000 npm start\" \"cross-env PORT=8000 npm start\""
  },
```

**Comment by NLKNguyen** [comment]
The issue is because the current `server.js` always listen on port 3000 regardless of the environment variable PORT, so the second instance can't work. `concurrently` or not doesn't make the instances listening on different ports.
Fixed here https://github.com/zeit/next-site/issues/355
