### ISSUE TITLE
Tutorial inconsistency, bundle analyzer errors, plus small commons.js.

### ISSUE THREAD

**Issue by aorsten** [zeit/next-site#115]
# Bug report

## Describe the bug

The "npm run analyze" command in the "Excel" tutorial on next.js does not produce the same analysis as the tutorial states.

Disclaimer: This may be the intended behaviour, but the tutorial does not match what I get - so please advise whether it should be this way.

## To Reproduce

I am following the next.js tutorial. I've had the same issue in both lesson 2 and 3, so I am going to use lesson 3. I have cloned the project, checked out the lesson, and ran "npm run analyze" - exactly as instructed in the tutorial.

At first, I get this window, and this error message in the console:
![image](https://user-images.githubusercontent.com/19666956/45614595-55961900-ba6a-11e8-8c9c-a8535079b85a.png)
![analysiserror](https://user-images.githubusercontent.com/19666956/45614731-b7568300-ba6a-11e8-8574-2591236e087c.PNG)

Now this does not at all look like what the tutorial says it should. I read a tip that the analyzer tries to open a new instance in the same port, and changed "server" to "static" in next.config.js. I then got 2 analyzer windows (one new), and no errors. This is the new analysis:

![image](https://user-images.githubusercontent.com/19666956/45614859-2502af00-ba6b-11e8-8753-731530f5108a.png)

This does not at all resemble the claim of highlight only being present in Commons.js

## Expected behavior
The expected behaviour is described here: https://nextjs.org/learn/excel/lazy-loading-components/analyze-result

## System information
 - OS: Windows 10
 - Browser: Chrome
 - Version of Next.js: 6.1.1
 - npm version: 6.4.1

**Comment by dennishn** [comment]
I am seeing the same issues with the excel tutorials, and it appears others are too:

#175 - it also has a link here, with the same issues being observed: https://github.com/arunoda/learnnextjs-demo/issues/45

**Comment by kheruc** [comment]
Thanks, we are in the process of updating all tutorials.
