### ISSUE TITLE
Logo Inconsistent

### ISSUE THREAD

**Issue by Brandoning** [zeit/next-site#117]
Homepage (/)
![screen shot 2019-01-21 at 16 54 38](https://user-images.githubusercontent.com/5629295/51488416-68fd1c00-1d9d-11e9-8f6a-5b8fcc765b1a.png)

/learn
![screen shot 2019-01-21 at 16 54 41](https://user-images.githubusercontent.com/5629295/51488427-72868400-1d9d-11e9-8cf9-82d19f2ad21d.png)

Not a huge difference but I noticed it briefly...

**Comment by timneutkens** [comment]
@Brandoning what browser / OS are you using? For me it renders the same way on both pages.
