### ISSUE TITLE
Add a next.config.js API Reference

### ISSUE THREAD

**Issue by glennreyes** [zeit/next-site#122]
Hi! I'm learning next.js at the moment and I've found it difficult to check out all the available options for `next.config.js` configuration. Specifically right now for example, I'm looking for all available options for `config.target` but can't see anything in the docs.

Although there are some helpful explanations about some configurations in the current docs, I'd love to have a simple table of all available options.

**Comment by mfix22** [comment]
@glennreyes I don't think `target` is released yet. It's part of Next 8 which is coming up soon 👍

**Comment by timneutkens** [comment]
Just for reference it's documented here until Next.js 8 is released: https://github.com/zeit/next.js#serverless-deployment

I think it'd make sense to add a complete reference though.

**Comment by Shaquu** [comment]
Well, I come to a place where I cannot find an option I used one day. Is there any reference already?

**Comment by lfades** [comment]
@Shaquu Will be added very soon 😌

**Comment by gugegev5** [comment]
> @Shaquu Will be added very soon 😌

can't wait

**Comment by gugegev5** [comment]
> @Shaquu Will be added very soon 😌

@lfades can't wait
