### ISSUE TITLE
Logo on non-retina screens doesn't render well

### ISSUE THREAD

**Issue by timothyis** [zeit/next-site#130]
When visiting Next.js from my external non-retina monitor, the logo looks like this:

![image](https://user-images.githubusercontent.com/1695613/52317772-54ce3700-29b9-11e9-9c08-b7d07b8fd58a.png)

**Comment by GiuMagnani** [comment]
@timothyis  Can I take this?

**Comment by GiuMagnani** [comment]
@timothyis could it be because the property `shape-rendering: crispEdges` of the `svg`? However, the `path` inside the `svg` has also the property `shape-rendering` but with the `geometricPrecision` value, so in theory that one should win (CSS specificity).

**Comment by Tomekmularczyk** [comment]
it looks fine on [ASUS E200H](https://www.asus.com/us/Laptops/ASUS-Vivobook-E200HA/specifications/) with 1366x768 pixel ratio (HD display):
![53142704_2308668179344935_8169578540648366080_n](https://user-images.githubusercontent.com/12544704/53696103-0ea3a200-3dc4-11e9-9900-951654be1c3b.png)
