### ISSUE TITLE
Documentation anchor links not properly scrolling in Chrome

### ISSUE THREAD

**Issue by vedraan** [zeit/next-site#132]
The anchor links in the documentation left sidebar menu are not functioning properly. Instead of taking you to the correct anchor they just scroll the page bit by bit until you reach the anchor.

Same thing if you land directly on a link containing an anchor e.g.
https://nextjs.org/docs#using-a-higher-order-component

Tested on OSX:
- Firefox: links work as expected
- Safari: links work as expected
- Chrome Version 72.0.3626.96 (Official Build) (64-bit) - fails to properly scroll

**Comment by YuriGor** [comment]
Confirm this. Even to make it scroll bit by bit you will need to click menu item twice. On first click nothing happens.

Kubuntu 18.04:
- Google Chrome Version 72.0.3626.96 (Official Build) (64-bit)
- Chromium Version 71.0.3578.98 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)

**Comment by YuriGor** [comment]
It was not aliased to production yet, but here
https://next-site-aevik4xfg.zeit.sh/docs/
scrolling is not smooth anymore.
