### ISSUE TITLE
How to configure nextjs for firebase hosting multisites

### ISSUE THREAD

**Issue by Modenu** [zeit/next-site#139]
Can't find examples on how to setup next with firebase hosting multisites. I updated the with-firebase-hosting to  support multisites, all my apps renders the default app content.
[files.zip](https://github.com/zeit/next-site/files/2847676/files.zip)

**Comment by timneutkens** [comment]
Feel free to send a pull-request.

**Comment by Modenu** [comment]
Got it to work. posted the code [https://stackoverflow.com/questions/54600401/how-can-i-setup-firebase-hosting-multisites-with-nextjs/54606641#54606641](stackoverflow)
