### ISSUE TITLE
Accessibility improvements

### ISSUE THREAD

**Issue by andresgalante** [zeit/next-site#163]
I think the website has some room to improve on accessibility, for example, there is no skip link, the navigation is not a nav or a list, there are aside elements not semantically correct, I haven't found a `main` area.

Is this something you are open to getting contributions?

**Comment by tryzniak** [comment]
Yeah, with this Google Chrome's Audit and axe are super helpful. Let's fix those issues!

**Comment by timneutkens** [comment]
Definitely open to contributions!

**Comment by timneutkens** [comment]
We landed a bunch of improvements with regards to this 👍
