### ISSUE TITLE
Marquee-like slider on homepage glitches after a few seconds

### ISSUE THREAD

**Issue by timneutkens** [zeit/next-site#18]
I guess the reason is that we're currently using `react-slick` to animate without stopping, which it wasn't built to do. Ideally, we use a real marquee like component, but so far I haven't found one. So we might have to roll our own. I have been trying a few CSS-only marquee solutions but they seem to break when you have more than a few items. Some requirements:

- [ ] Should be rendered with SSR / static export
- [ ] Uses react-transition-group when possible (since we use it for /showcase already)
- [ ] Items should be visible immediately when loading the page, and then start the marquee
- [ ] Transition has to be smooth, right now it glitches after a few seconds

The current component can be found here:

https://github.com/zeit/next-site/blob/master/components/home/showcase/company-slider.js

**Comment by timneutkens** [comment]
Slowing down hides the issue quite a bit, but it's definitely there, the bottom line is that react-slick is not made to do marquee like animations.

**Comment by quietshu** [comment]
Fixed with the new website.
