### ISSUE TITLE
Thanks. Looking for the backend git repo

### ISSUE THREAD

**Issue by lvnilesh** [zeit/next-site#180]
Thanks for sharing the code for next-site frontend. It is an awesome example for truly learning nextjs. It would help to also understand the corresponding code for https://learn-server.nextjs.org 

Appreciate if you can please open source that as well. Thanks.

**Comment by timneutkens** [comment]
We're planning to retire the learn-server. It's an instance of https://github.com/arunoda/coursebook-server

**Comment by lvnilesh** [comment]
What is the new login/auth tooling that you use with https://nextjs.org/learn/

**Comment by timneutkens** [comment]
I'm not sure what you're referring to 🤔

**Comment by lvnilesh** [comment]
Older coursebook code connected that learn frontend to a backend coursebook server which used github api to provide login method.

Where is the code for newer backend that allows login with github button on the learn subsite?

**Comment by lfades** [comment]
@lvnilesh It's not public unfortunately, but it's a very simple auth with github setup using Passport.js
