### ISSUE TITLE
refresh page & 404 bug

### ISSUE THREAD

**Issue by xgqfrms** [zeit/next-site#192]
# Examples bug report

> refresh page & 404 bug

https://nextjs.org/learn/basics/server-side-support-for-clean-urls

![refresh-next-bug](https://user-images.githubusercontent.com/7291672/53384206-0eb33480-39b5-11e9-857f-a4f9e0b7e50f.gif)

## source codes

https://github.com/xgqfrms/SSR-All-In-One/tree/master/next-demo-app

**Comment by Tomekmularczyk** [comment]
I have followed steps on next-site and it all worked for me.

@xgqfrms it seems to me that after creating a server.js and copying the files you forgot to restart the dev server :)

I also cloned the repository you have provided (it's different than next example now) and it seems that you got this working :)

http://recordit.co/3cyD2Rgbqa

**Comment by xgqfrms** [comment]
@Tomekmularczyk Thanks for your time!

I think that is my changes caused the error and I will try it again later.

**Comment by timneutkens** [comment]
🙏
