### ISSUE TITLE
Problem with Nextjs official website on Google search?

### ISSUE THREAD

**Issue by MiloshN** [zeit/next-site#193]
I jumped to Nextjs to reading something from my phone and seeing something like this. Problem with Nextjs official website.
I don't know, maybe are problem with my browser, but I am not sure, my Google Chrome is on latest version.
Link of problem here : https://ibb.co/HgS8BWj

Posted from my phone.

**Comment by kheruc** [comment]
I checked this on a couple of mobile devices and browsers, but didn't see the problem. Maybe it was a temporary issue, can you check again?

**Comment by timneutkens** [comment]
It was fixed last week by @mfix22
