### ISSUE TITLE
How to update https://nextjs.org/learn/?

### ISSUE THREAD

**Issue by Jared-Dev** [zeit/next-site#21]
When attempting to go through the tutorial I hit a "bug" during the first dev server startup where it wasn't able to build the component. I ended up needing to explicitly add `babel-core@latest` and `babel-loader@latest` via npm to resolve the error. I was trying to find the repo for this so I could just submit a PR, but I'm having difficulty locating that. If it is something I can update feel free to point me in the right direction. Otherwise, could this please be updated in the docs?

**Comment by timneutkens** [comment]
I just combined all repositories for nextjs.org in this repository. The content of /learn is in the `learn-content` directory 👍
