### ISSUE TITLE
IE 11 regression with v8

### ISSUE THREAD

**Issue by oliviertassinari** [zeit/next-site#218]
# Bug report

## Describe the bug

The page doesn't load on IE 11.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Visit https://nextjs.org

## Expected behavior
The page loads on IE 11.

## Screenshots

![capture d ecran 2019-03-06 a 23 15 27](https://user-images.githubusercontent.com/3165635/53918019-36199980-4066-11e9-974c-e223676239a3.png)

## System information
 - OS: Windows 10
 - Browser: IE 11
 - Version of Next.js: 8.0.0

## Additional context

Are you guys considering adding IE 11 in the test suite? It's a chronic issue, I fear IE 11 is hear to stay at least for 2020 in the user browser share.

- #3755
- #5499
- #1138
- #4187 
- #4334

**Comment by ijjk** [comment]
After investigating, it looks like if you comment out the below lines from `www/lib/polyfill.js` and re-build, the `WeakSet` error goes away and the page no longer crashes with `An unexpected error has occurred` in IE 11. 

```js
if (!Object.entries) {
  Object.entries = function(obj) {
    var ownProps = Object.keys(obj),
      i = ownProps.length,
      resArray = new Array(i);
    while (i--) {
      resArray[i] = [ownProps[i], obj[ownProps[i]]];
    }
    return resArray;
  };
}

if (!String.prototype.startsWith) {
  String.prototype.startsWith = function(searchString, position) {
    position = position || 0;
    return this.indexOf(searchString, position) === position;
  };
}
```

**Comment by oliviertassinari** [comment]
Did you move the issue from https://github.com/zeit/next.js to https://github.com/zeit/next-site? I was able to reproduce the same problem on Material-UI side. If I understand it correctly, it's a coïncidence that both sites are broken at the same time?

**Comment by timneutkens** [comment]
@oliviertassinari @ijjk tried running plain Next.js on IE11 last night and there were no issues, so indeed. We'll be running tests again IE11 and a few other browsers 🔜 just to be on the safe side of things.

**Comment by oliviertassinari** [comment]
@timneutkens I have tried the same, I confirm.

**Comment by oliviertassinari** [comment]
Ok, I have found it, it's a problem with `next/head`:

```jsx
import React from 'react';
import NextHead from 'next/head';

class HomePage extends React.Component {
  render() {
    return (
      <div>
        <NextHead>
          <title>title</title>
        </NextHead>
        nasty
      </div>
    );
  }
}

export default HomePage;
```

**Comment by oliviertassinari** [comment]
I can solve the IE 11 crash by removing the usage of `next/head`. However, using `next/head` alone in a simple Next.js setup is not enough. I need to add by `babel.config.js` file.

**Comment by oliviertassinari** [comment]
Ok, I have figured it out, `['@babel/plugin-transform-runtime', { corejs: 2 }],` (corejs: 2) is required.

**Comment by timneutkens** [comment]
```
[require('@babel/plugin-transform-runtime'), {
        corejs: 2,
        helpers: true,
        regenerator: true,
        useESModules: supportsESM && presetEnvConfig.modules !== 'commonjs',
        ...options['transform-runtime']
      }],
```

That's part of next/babel though 🤔

**Comment by oliviertassinari** [comment]
Problem solved: https://github.com/mui-org/material-ui/pull/14781.

**Comment by timneutkens** [comment]
Hmm so you're not using `next/babel`?

**Comment by oliviertassinari** [comment]
Let me try with `next/babel` preset.

**Comment by oliviertassinari** [comment]
Good idea, I'm trying that out :)

**Comment by timneutkens** [comment]
💯

**Comment by timneutkens** [comment]
Fixed in https://github.com/zeit/next-site/pull/221
