### ISSUE TITLE
When trying complete the tutorial with a Github credential sometimes a logout suddenly happens

### ISSUE THREAD

**Issue by diegonvs** [zeit/next-site#226]
<img width="1280" alt="Screen Shot 2019-03-09 at 01 05 36" src="https://user-images.githubusercontent.com/7663513/54066024-c80cd800-4207-11e9-965f-78cd4ea787bf.png">

- This error only occurs when trying answer the questionnaire to advance in another tutorial step.
- I verified my machine to not remove page or app cache during the navigation but the error persists.
- Reproduced on Chrome 72, macOS Mohave.

**Comment by timneutkens** [comment]
This should be fixed by the move to MDX 🙏
