### ISSUE TITLE
add details on how to set ENV when using serverless now v2 with build time env for local machine and on now platform

### ISSUE THREAD

**Issue by williamli** [zeit/next-site#247]
add to guide on how to use build.env in `now config json` files and use them in local machine and on now v2.

i.e.

use `now-env` to expose runtime env to Next app on local machine

```
// next.config.js

if (process.env.NODE_ENV !== 'production') {
  require('now-env')
}
```

use build-time env in now v2

and use export env to frontend with

```
// next.config.js

const nextConfig = {
  target: 'serverless',
  env: {
    ENV: process.env.ENV
  }
...
```

**Comment by williamli** [comment]
Similar to https://github.com/zeit/docs/issues/637, good to have a info related to this on both sites for reference.

There are few posts on Spectrum with problems related to defining ENV in now.json as `env` instead of `build.env`.

**Comment by timneutkens** [comment]
Closing this in favor of zeit/docs#637 as we'll have a new guide on the docs.
