### ISSUE TITLE
 next.js website scroll behaviour buggy in FF 62.0

### ISSUE THREAD

**Issue by mweibel** [zeit/next-site#27]
When scrolling in Firefox 62.0 on the next website docs, the scroll position is reset when reaching the "Automatic code splitting" section.

See screen recording attached.
![nextjs](https://user-images.githubusercontent.com/307427/42166890-ae567cbe-7e0c-11e8-8ca9-8887ef1a5bed.gif)

**Comment by quietshu** [comment]
@mweibel thanks for reporting!
I can't reproduce this issue with the new website. Could you confirm?

**Comment by mweibel** [comment]
Me neither, great :) thanks!

**Comment by quietshu** [comment]
Awesome, thanks.
