### ISSUE TITLE
Bug(Learn): Deploying a Next.js App - Unclear Info/More Info needed

### ISSUE THREAD

**Issue by co16353sidak** [zeit/next-site#280]
URL : https://nextjs.org/learn/basics/deploying-a-nextjs-app/deploying-to-zeit-now

> Finally, install Now and run the following command:
1. This step should be elaborated more as in what the user will install, the link redirects to the main now webpage and user has no understanding as to how to go about setting this up, a solution could be to link the downloads page with a brief intro to `now-cli`
> Here, we mentioned port 8000 as the port in which we start our app. But we didn't change it when deploying to ZEIT Now.
2. Here like every other question, there is a hint to tell the user where he/she has to look, there is no way in understanding whether at which port we are accessing the deployed app. therefore many who reach this point won't know where to look or maybe even not understand this, some more explanation and guidance could be needed here.

**Comment by lfades** [comment]
Handled by #385
