### ISSUE TITLE
Gradient banding on blog footer

### ISSUE THREAD

**Issue by skllcrn** [zeit/next-site#292]
Seeing some very slight banding on an @1x display in the footer at nextjs.org/blog. Could a potential solution be to soften it up a bit by making the gradient go from #222 to #333?

![image](https://user-images.githubusercontent.com/8440026/55180038-05baac00-5189-11e9-9149-e253cbd3f807.png)

**Comment by lfades** [comment]
I'm unable to reproduce this and Idk if this is the case anymore, @skllcrn please reopen if the issue persists 🙏
