### ISSUE TITLE
Site bug

### ISSUE THREAD

**Issue by dmytropanontko** [zeit/next-site#316]
Hi all, you have the UI bug on your site

![image](https://user-images.githubusercontent.com/37536815/56726248-0d08b180-6757-11e9-8142-9bcf5a9c8c7f.png)

I use Dell Inspiration 5577 15"

**Comment by timneutkens** [comment]
Feel free to investigate/fix it, the repository is open source: github.com/zeit/next-site.

**Comment by marcorichetta** [comment]
Changing the `box-sizing` property to `content-box` adds space between components, but it applies to every element of the page.
https://github.com/zeit/next-site/blob/212912b9563ed8e8329f5c8010009c3eee11811a/www/components/page.js#L36

![imagen](https://user-images.githubusercontent.com/19599150/57960031-ff20f900-78dc-11e9-9c05-9352e7439f13.png)
***
In addition to that, it needs some bottom padding on the sidebar.
![imagen](https://user-images.githubusercontent.com/19599150/57960479-51631980-78df-11e9-93c6-ee09f138583f.png)

Another option is to modify only the `documentation-container` class.

There is some guide on applying CSS rules on Next.js or Zeit sites?
