### ISSUE TITLE
Inconsistent imports across `/learn`

### ISSUE THREAD

**Issue by ganlub** [zeit/next-site#321]
This issue makes reference to the PR #320.

Imports are not consistent across `/learn`, check for example how the Header and Layout component are imported [here](https://github.com/zeit/next-site/blob/master/learn/pages/learn/basics/using-shared-components/the-layout-component.mdx).

Let's provide a consistent use of file extensions across `/learn`. Let me know if you rather want to enforce this or disallow said extensions and I'll make the required changes. If it is the first, then the mentioned PR could be merged.

**Comment by lfades** [comment]
Closing this because it's not the case anymore, thank you.
