### ISSUE TITLE
micro proxy is deprecated

### ISSUE THREAD

**Issue by Xiphe** [zeit/next-site#333]
The docs currently suggest using [micro-proxy](https://github.com/zeit/micro-proxy) in the ["Multi Zones/How to merge them" section](https://github.com/zeit/next-site/blob/fcedf0019162a3eb47a6fe6038c9844ea19619c3/www/components/docs/docs.mdx#how-to-merge-them). But the project is unmaintained in favour of the now-cli.

1. From reading the now-cli docs its not obvious to me how to configure a proxy + i'm not using now, so using the cli just for a proxy seems odd.
2. The next docs should not point to an unmaintained resource. 

I'm happy to provide a PR for this but am not sure what the ideal setup would be.

---

Context: I'm trying to provide a minimal replication for https://github.com/zeit/next.js/issues/7488 so that the issue can be debugged locally.

**Comment by lfades** [comment]
Hi @Xiphe, the docs are currently using the `master` branch of Next.js, once `master` is updated the docs will be updated too.

**Comment by Xiphe** [comment]
In which way i the nextjs `master` related to the issue? I don't understand what you mean with "using".

**Comment by lfades** [comment]
@Xiphe is related because the docs here are the readme in the next.js repo, is has to be updated there, it will happen so thank you for the report 👍

**Comment by Xiphe** [comment]
Ah I get it. Thanks. Let me know when I can help.

**Comment by lfades** [comment]
Closing this now that micro-proxy has dissapeared from Next.js docs 💃
