### ISSUE TITLE
Link to https://github.com/zeit/next-site from https://nextjs.org/

### ISSUE THREAD

**Issue by plug-n-play** [zeit/next-site#349]
https://nextjs.org/ is the official public interface of  Next.js including getting started, documentation, and guides.

For anyone who wants to report a bug to this website, request a guide, or just a small enhancement, a link to this official source repo https://github.com/zeit/next-site is not available on https://nextjs.org/

It would be great to add this link to encourage such requests.

May be in the footer and/or other logical places(FAQs may be) ?

**Comment by lfades** [comment]
I'm closing this because issues in the Next.js repo regarding this site are also welcome 👍
