### ISSUE TITLE
Ability to search documentation from Header

### ISSUE THREAD

**Issue by plug-n-play** [zeit/next-site#353]
Just like https://zeit.co/docs it would be nice to have an ability to search the documentation for nextjs.org from the header

**Comment by lfades** [comment]
@plug-n-play the search in https://zeit.co/docs is awesome, there's a difference though, in https://nextjs.org/docs everything is in a single page, so the usual search with `ctrl + f` works fine.

**Comment by plug-n-play** [comment]
@lfades - sorry, I didn't follow. Say I am on https://nextjs.org/ and want to search `AMP in Next.js` , how would `ctrl/mac + f` help ? In this case, I would expect search results to show `https://nextjs.org/blog/next-8-1#amp-in-nextjs`

**Comment by lfades** [comment]
@plug-n-play We don't have anything like that for now
