### ISSUE TITLE
Bug and Fix: Deploying a Next.js App / Run two instances

### ISSUE THREAD

**Issue by NLKNguyen** [zeit/next-site#355]
Hi,

With the current instruction, it is not possible to run two instances with different ports because the current server.js still uses a constant port value of 3000
https://github.com/zeit/next-learn-demo/blob/e407e066564b1ac05aa3df0d9505e176b7c8d154/8-deploying/server.js#L23

So, no matter what the value of PORT variable is, it still listens on port 3000, and the second instance trying to listen on the same port will crash.
![Screenshot from 2019-06-26 15-16-23](https://user-images.githubusercontent.com/4667129/60218907-95720400-9825-11e9-87df-19cc3fc14bd1.png)
![Screenshot from 2019-06-26 15-17-18](https://user-images.githubusercontent.com/4667129/60218915-9a36b800-9825-11e9-9411-8f74d99e11bb.png)

It can be fixed easily in `server.js` by getting the port number if provided, or default to 3000 otherwise so that `npm run dev` without port will still work.
```js
const port = process.env.PORT || 3000
```

```js
    server.listen(port, err => {
      if (err) throw err
      console.log(`> Ready on http://localhost:${port}`)
    })
```
![Screenshot from 2019-06-26 15-27-22](https://user-images.githubusercontent.com/4667129/60219385-154c9e00-9827-11e9-8f0e-57096625f8f3.png)

I can make a PR for this fix, but that will need to be updated on all `server.js` in other lessons for consistency, so perhaps the author might want to instruct the code change in this lesson only.

**Comment by lfades** [comment]
Custom servers are no longer part of /learn lessons since https://github.com/zeit/next-learn-demo/pull/12.
