### ISSUE TITLE
Documentation Suggestion: mdx-js/tag now mdx-js/react

### ISSUE THREAD

**Issue by agstover** [zeit/next-site#358]
I don't know if this is something you want to address here, but since this is the place NextJS team often points to as example of how to setup NextJS + MDX, it might be helpful to point out that apparent that in current version of MDX, the MDX provider should come from mdx-js/react instead of mdx-js/tag. I was using /tag as shown here in this site, and my component styles weren't being transferred. Checked MDX docs and they showed /react. Changed to that and everything worked.

**Comment by timneutkens** [comment]
> but since this is the place NextJS team often points to as example of how to setup NextJS + MDX

Can't say that I often point here.

Feel free to open a PR to upgrade mdx 👍🙏
