### ISSUE TITLE
Lazy Loading Components get an "Cannot read property 'querySelectorAll' of null" error

### ISSUE THREAD

**Issue by nicu-chiciuc** [zeit/next-site#39]
# Examples bug report

## Example name
Lazy Loading Components

## Describe the bug
After following all the steps and running the app, visiting `http://localhost:3000/p/hello-nextjs` will output the error `Cannot read property 'querySelectorAll' of null` with a stack trace.

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:
1. Go to https://nextjs.org/learn/excel/lazy-loading-components/setup
2. Follow the steps
3. Visit http://localhost:3000/p/hello-nextjs

## Expected behavior
It is expected to not have an error.

## Screenshots
![capture](https://user-images.githubusercontent.com/4076804/43784792-9d5578de-9a6d-11e8-9bb4-652bc463c4ea.PNG)

## System information
 - OS: Windows 10 Pro
 - Version of Next.js: 6.1.1
 - Node: v10.8.0
 - npm: 6.1.0

**Comment by yurynix** [comment]
I've got the same issue

* OS: macOS High Sierra 10.13.6 ( `Darwin local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64` )
* Version of Next.js: 4.2.3
* Node: v10.7.0
* npm: 6.1.0

Solved by:
```
diff --git a/package.json b/package.json
index 3d425ef..0e55965 100644
--- a/package.json
+++ b/package.json
@@ -15,10 +15,10 @@
   "dependencies": {
     "cross-env": "^5.0.1",
     "marked": "^0.3.6",
-    "next": "^4.2.0",
+    "next": "^6.1.1",
     "react": "^16.2.0",
     "react-dom": "^16.2.0",
-    "react-highlight": "^0.10.0",
+    "react-highlight": "^0.12.0",
     "webpack-bundle-analyzer": "^2.8.3"
   }
 }
```

**Comment by timneutkens** [comment]
https://github.com/arunoda/learnnextjs-demo/pull/35
