### ISSUE TITLE
Lazy Loading Components with `dynamic()` function vs promise

### ISSUE THREAD

**Issue by dosentmatter** [zeit/next-site#398]
Should `const Highlight = dynamic(import('react-highlight'));` instead be `const Highlight = dynamic(() => import('react-highlight'));`?
https://github.com/zeit/next-site/blame/f2dae13980ccbae4517dcb524d89d29f4651cb89/pages/learn/excel/lazy-loading-components/hello-dynamic-components.mdx#L67

I see the [docs](https://nextjs.org/docs/#dynamic-import) only show the function form and not the raw promise `import()` form.

My guess is that if you use the function form, you delay the import and the module will only be imported if you use `Highlight`.
If you use the promise form, the module will be imported immediately on page load but the `dynamic` wrapper is still used for the default loading component. This happens because the promise has been triggered. Is that correct? I can't find any docs on the differences.

If my guess is correct, in the [nextjs lazy loading components tutorial](https://nextjs.org/learn/excel/lazy-loading-components/load-only-if-needed), the goal is to load `Highlight` only if used. Shouldn't the function form be used instead then? Otherwise, the promise form would make `'react-highlight'` load immediately on page load.

**Comment by timneutkens** [comment]
Hey! Thanks for asking about this, actually `dynamic(import())` is codemodded at build time to `dynamic(() => import())`, the correct usage is to always use the function 👍

**Comment by dosentmatter** [comment]
Good to know. Thanks for the clarification!
