### ISSUE TITLE
Next.js documentation side-nav should auto scroll

### ISSUE THREAD

**Issue by Timer** [zeit/next-site#422]
As the user scrolls through the documentation we should automatically scroll the side navigation bar and bold the entry they're looking at.

**Comment by Windrushfarer** [comment]
Would just bolding links be enough?

**Comment by Timer** [comment]
I think we'd really want it to automatically scroll the panel. Colors would be a great first start, though.

**Comment by Windrushfarer** [comment]
What color would be better at your point of view?

**Comment by Timer** [comment]
Maybe solid black + a heavier font weight?

**Comment by teleginzhenya** [comment]
I'd like to work on this feature (:

**Comment by Timer** [comment]
@teleginzhenya you can take this up if @Windrushfarer doesn't have enough time! Do mind, this will require programming in AMP (and not plain React lifecycles).

**Comment by teleginzhenya** [comment]
> Can you check if it works without using React.memo? Also if you want to use React hooks instead please go ahead, it may get you a better understading about what's happening.
> 
> @teleginzhenya Because this is an issue with your fork and not with the project itself I'm closing it. Please continue the conversation in the respective issue: #422

@lfades I tried to use hooks for this, but unfortunately got rerender everytime, removing React.memo didn't help :[

**Comment by timneutkens** [comment]
Covered by the new docs.
