### ISSUE TITLE
"An unexpected error has occurred" in learn pages

### ISSUE THREAD

**Issue by EslamHiko** [zeit/next-site#431]
I get `An unexpected error has occurred` every time I visit anything related to `learn` whether I'm logged in or as a guest.

The left side is from Google Chrome Logged In. 
The right side is from Firefox Developer Edition as a guest.

![error](https://user-images.githubusercontent.com/18349358/65892735-1ac9ff00-e3a7-11e9-9049-bb3b848b546b.PNG)

I think it's related to the latest PR, it was working like 5-7 hours ago.

**Comment by zomars** [comment]
I've tried to report this in the wrong repo. Some details:

- Disabling javascript let's me see the content
- Console returns this:


<img width="614" alt="image" src="https://user-images.githubusercontent.com/3504472/65893317-ffd69b00-e364-11e9-843f-fef05e744ff7.png">

**Comment by Timer** [comment]
Sorry about this, just fixed!
