### ISSUE TITLE
unlock bodyLocker when out of navigation toggle mode

### ISSUE THREAD

**Issue by LiebeG** [zeit/next-site#459]
Navigation toggle mode changes along with the window width.
I found if you toggled the nav icon in nav active mode and change back to inactive mode without toggle again. Then the page is locked, since the css property `overflow: hidden;` under `<body>` tag.

UPDATE:
1. Because the responsive feature, if the window width is less than certain value, we will get a collapsible navigation bar(toggle). See below:
![Screen Shot 2019-10-24 at 1 01 36 PM](https://user-images.githubusercontent.com/6782188/67455074-f9cf9380-f65e-11e9-9599-b63a7e6ab5fd.jpg)
2. Click the toggle, we get the menu
![Screen Shot 2019-10-24 at 1 02 06 PM](https://user-images.githubusercontent.com/6782188/67455075-f9cf9380-f65e-11e9-9eba-9a7aa4cb1eb2.jpg)
3. If I don't click the 'close' icon then increasing window width directly to get the full nav, the page body is locked.
![Screen Shot 2019-10-24 at 1 02 48 PM](https://user-images.githubusercontent.com/6782188/67455076-f9cf9380-f65e-11e9-9c63-a38778874e87.jpg)
4. Because the css property on `<body>` tag: `overflow: hidden`, the `<html>` only get height `428px` -> CANNOT scroll down the page anymore, unlock the body only if I change back to toggle nav and click the close icon.
![Screen Shot 2019-10-24 at 1 03 09 PM](https://user-images.githubusercontent.com/6782188/67455077-fa682a00-f65e-11e9-8749-0ac65790e75e.jpg)
5. But actually the body height is `2418px`.
![Screen Shot 2019-10-24 at 1 03 16 PM](https://user-images.githubusercontent.com/6782188/67455078-fa682a00-f65e-11e9-96a3-49eae3a5cc1d.jpg)

**Comment by lfades** [comment]
Hello @echoyangyang thank you for the bug report, do you mind sharing more details about the issue? My simple mind doesn't understand 😔 but I want to 🤩.

**Comment by echoyangyang** [comment]
> Hello @echoyangyang thank you for the bug report, do you mind sharing more details about the issue? My simple mind doesn't understand 😔 but I want to 🤩.

😨Sorry my poor narrative! Please check what I update in issue. 😉

**Comment by timneutkens** [comment]
Looks like this relates to zeit.co/docs instead of nextjs.org, cc @timothyis 

https://github.com/zeit/docs/issues
