### ISSUE TITLE
Docs for older version

### ISSUE THREAD

**Issue by ritesh-pandey** [zeit/next-site#460]
How do I access docs for older versions?

I have a project built on Next.js version `6.1.1`.  It was the latest version when the project began. For development/maintenance, I need to refer to Next.js documentation regularly. But there is no way to find it, except probably to read the `readme.md` file.

Do we have any other solution (preferably a hosted one)?

**Comment by lfades** [comment]
@ritesh-pandey We only have the docs for the latest version in the Next.js website.

The docs are the readme from the Next.js repo, so if you need the docs for any particular version, you can pick a [release](https://github.com/zeit/next.js/releases) and read the readme there 😌
