### ISSUE TITLE
Horizontal scroll gap on landing page

### ISSUE THREAD

**Issue by janko** [zeit/next-site#508]
The pictures in the "Who's Using Next.js" section are overflowing for me, creating an additional gap that allows for horizontal scrolling.

<img width="1280" alt="Screenshot 2020-01-07 at 15 51 24" src="https://user-images.githubusercontent.com/795488/71904117-d00a1100-3165-11ea-9120-b50ca0389252.png">

I see this on both Firefox 71.0 and Chrome 79.0, macOS Catalina 10.15.1.

**Comment by lfades** [comment]
That's bad and needs to be fixed, thank your for the report, what's your screen resolution? 🙏  - In my case it only happens when I zoom in the page.
