### ISSUE TITLE
[RFC] Streamline /learn Basics examples

### ISSUE THREAD

**Issue by chibicode** [zeit/next-site#533]
## Issue

I was working on updating [the "Styling Components" lesson](https://nextjs.org/learn/basics/styling-components) on `/learn` and found that the structure of basics lessons can be improved.

https://nextjs.org/learn

Right now, the first 5 lessons involve building a blog app. Then,

- Lesson 6 (fetching data) is about building a TV show app
- In lesson 7 (styling), you revert the changes from lesson 6 and go back to the blog app
- In lesson 8 (API routes), you start from scratch and create a quotes app
- In lesson 9 (deploying), you go back to the blog app and deploy it.

![lessons-streamline](https://user-images.githubusercontent.com/992008/72668506-7c58bc80-39dc-11ea-867a-396c5754a40d.png)

As a result, in lessons 7 - 9, you won't be able to continue directly from the previous lesson - you have to download new starter code. It also requires readers some mental context switching because you'll be going back and forth between TV app, blog app, quotes app, etc. I think this can be prevented.

## Suggestions

- **Simpler solution:** Move lessons around so that the blog app lessons are all grouped together. That means that the "styling" lesson and the "deploy" lesson (both related to the blog app) will be moved up, and the "fetching data" lesson and the "API routes" lesson will be moved down.
- **Better solution:** I think we can make ALL "basic" lessons to be related to building a blog app. So for the "fetching data" lesson, instead of building a TV show app, we'll explain fetching data in the context of a blog app. And for API routes, instead of building a quotes app, we'll create some API routes inside a blog. I think having a consistent theme (building a blog app) throughout the basics lessons will streamline the experience and reduce the reader's cognitive load.

What do you think? I can implement both solutions, but personally I like the second solution.

## FYI

[I've written an article about improving coding tutorials](https://ts.chibicode.com/refactor/). Here's the relevant section:

<img width="510" alt="Screen Shot 2020-01-18 at 11 16 04 AM" src="https://user-images.githubusercontent.com/992008/72669215-f476b080-39e3-11ea-8996-cd025dc8ce22.png">

cc @lfades

**Comment by timneutkens** [comment]
Sounds great to me 💯

**Comment by chibicode** [comment]
Closed by https://github.com/zeit/next-site/pull/610
