### ISSUE TITLE
Migrate next-learn-demo into this repo?

### ISSUE THREAD

**Issue by chibicode** [zeit/next-site#534]
It seems that we're using the monorepo pattern for other projects, so why not migrate [next-learn-demo](https://github.com/zeit/next-learn-demo) into this repo?

When we update the content on `/learn/*` pages in this repo, we often need to update [next-learn-demo](https://github.com/zeit/next-learn-demo) to make sure that's in sync, resulting in 2 PRs. By moving them here, you just need to make 1 PR, and that's easier to maintain. ([next-learn-demo](https://github.com/zeit/next-learn-demo) doesn't even have issues tab!)

The downside is that, on [a setup page](http://localhost:3000/learn/basics/navigate-between-pages/setup), they'll have to clone this repo instead, which is larger. [There's no easy way to download a single directory on GitHub from CLI](https://stackoverflow.com/questions/7106012/download-a-single-folder-or-directory-from-a-github-repo).

I can work on this if it makes sense.

cc @lfades

**Comment by timneutkens** [comment]
@chibicode this repo is significantly larger, hence why the demo apps are in a separate repo 👍
