### ISSUE TITLE
Old docs: The Notification bar doesn't span full width

### ISSUE THREAD

**Issue by chibicode** [zeit/next-site#548]
https://nextjs.org/docs/old

The bar that says **Note:** ... is not spanning full width:

<img width="1027" alt="Screen Shot 2020-01-28 at 5 10 17 PM" src="https://user-images.githubusercontent.com/992008/73319387-1c8abe80-41f1-11ea-808a-0144e5e49257.png">

**Comment by lfades** [comment]
The issue is in it not taking the entire space and then being centered, currently it takes as much as the text needs
