### ISSUE TITLE
https://nextjs.org/learn/basics/api-routes/fetching-api-routes does not show contents of quotes.json

### ISSUE THREAD

**Issue by dhurlburtusa** [zeit/next-site#549]
The code at https://nextjs.org/learn/basics/api-routes/fetching-api-routes imports ../../quotes.json but none of the tutorial pages show the contents of quotes.json.

Also, it should say you need to npm install --save swr.

**Comment by lfades** [comment]
@dhurlburtusa `quotes.json` is included in the [demo](https://github.com/zeit/next-learn-demo/blob/master/7.2-api-routes/quotes.json), and [`swr`](https://github.com/zeit/next-learn-demo/blob/master/7.2-api-routes/package.json#L14) is already in the demo's packages.

Did you have any issues getting the demo working or understanding it?

**Comment by dhurlburtusa** [comment]
As I was going through the tutorial, everything was thorough and complete until I got to this page. If there was an npm package to install, then the tutorial explicitly stated it. That, obviously, was easy enough to figure out on my own. Regarding `quotes.json`, I completely forgot about the demo. Regardless, I think it would improve the page if it at least linked to `quotes.json` in the demo repo.
If I find time, I'll create a PR for these changes if you think the team would accept them.

**Comment by lfades** [comment]
You install `swr` right after downloading the demo, alongside the other packages (Next.js, react, e.t.c), because it's already in the dependencies.

We don't explain the `quotes.json` file, but we do add a link to it in the steps, it's an import for the file, and the code would only work if that file exists, and it does. The demo repo doesn't link to it because it's only the initial setup, the finished app is there when you finish with the steps.

**Comment by dhurlburtusa** [comment]
Okay, I think I see the perspective you are coming from. You are actually expecting the user to
```sh
git clone https://github.com/zeit/next-learn-demo.git
cd next-learn-demo
cd 7.2-api-routes
npm install
npm run dev
```
for this particular part of the tutorial. If I do that, then everything makes sense and I have the `quotes.json` available.

I am coming from the perspective that I just worked through the previous 7 steps in the tutorial. All of them, except "Getting Started", have a "Setup" section (e.g., https://nextjs.org/learn/basics/navigate-between-pages/setup). This first setup section says I can either clone the demo or continue from the previous tutorial (i.e., "Getting Started" in this case). So, for the subsequent tutorials ("Using Shared Components", "Create Dynamic Pages", "Clean URLs with Dynamic Routing", "Fetching Data for Pages", and "Styling Components"), I just continued with the project I started with from the "Getting Started" tutorial. I had no issues. Once I got to the "API Routes" tutorial, you can't just continue where the last tutorials left off. I didn't realize that because I had not issues we the previous tutorials, and so I pretty much just clicked ahead from https://nextjs.org/learn/basics/api-routes/setup.

Now that I better understand where I made the mistake (not cloning and cd'ing to 7.2-api-routes), my suggest is to make it more clear that you can't just continue from where the previous tutorials left off. This can be accomplished with doing one or more of the following:
- On https://nextjs.org/learn/basics/navigate-between-pages/setup, don't suggest that you can continue your work from the previous lesson. Get users in the habit of cloning and cd'ing to the correct directory.
- On https://nextjs.org/learn/basics/api-routes/fetching-api-routes, link to https://github.com/zeit/next-learn-demo/blob/master/7.2-api-routes/quotes.json so that users can continue where they left off.
- On https://github.com/zeit/next-learn-demo/blob/master/7.2-api-routes/quotes.json, add the following code block:
```
npm install swr
```
- On https://nextjs.org/learn/basics/api-routes/setup, make it hard to proceed to the next lesson unless they cloned the demo repo and cd'ed into the correct directory.

The reason I made the mistake of continuing where the previous lesson/tutorial left off was because that was suggested in https://nextjs.org/learn/basics/navigate-between-pages/setup and all the "Setup" sections in the different tutorials have the same structure and look almost identical.

Don't get me wrong, I think you guy's did a great job with the tutorial/learn demo but this is one area where I think can be improved upon. Thanks for listening. I hope you take my suggestion serious. I do realize that I made the mistake by not following the instructions to a T, but I am guessing I am not the first one to trip up on this either.

If you want me to make a PR with the above suggestions, please let me know which suggestions you like. I'll be glad to spend about an hour to help future users.

**Comment by lfades** [comment]
@dhurlburtusa Thank you, so you're 100% right, our lessons are not really connected anymore and a setup per lesson is not ideal, or at least we should be more clear about all of this. I'll leave the issue open until it's fixed, hopefully very soon.

@chibicode This is related to the changes you're doing.

**Comment by chibicode** [comment]
Hi @dhurlburtusa, I agree 100% with your comment. We're working on fixing this. I noticed the exact same problem and wrote up this issue 12 days ago: https://github.com/zeit/next-site/issues/533

**Comment by chibicode** [comment]
We've shipped [the brand new Learn lessons today](https://nextjs.org/learn) - now all the examples are connected and you can continue from Nth lesson to (N+1)th lesson without fetching a new repo!

https://github.com/zeit/next-site/pull/610
