### ISSUE TITLE
Webpack Bundle Analyzer Output Does Not Match Well with Quiz Choices

### ISSUE THREAD

**Issue by dhurlburtusa** [zeit/next-site#556]
On https://nextjs.org/learn/excel/lazy-loading-modules/analyze-the-app, the choices given don't match well with the client Webpack Bundle Analyzer output.

![screencapture-file-C-code-play-nextjs-next-learn-demo-E2-lazy-loading-modules-next-analyze-client-html-2020-01-29-18_17_05](https://user-images.githubusercontent.com/4006431/73411953-5b3d7900-42c4-11ea-82b1-6c1803fed784.png)

![screencapture-nextjs-org-learn-excel-lazy-loading-modules-analyze-the-app-2020-01-29-18_20_19](https://user-images.githubusercontent.com/4006431/73411966-698b9500-42c4-11ea-8b38-c3f39260f507.png)

The only reason I got the answer right was because I saw two chunks had the Firebase modules. There was only one answer that listed two modules. But the chunk file names nowhere match with choice C.

After going to https://nextjs.org/learn/excel/lazy-loading-modules/analyze-result, it looks like maybe the webpack configuration has changed.

Just found out that there is a similar issue at https://nextjs.org/learn/excel/lazy-loading-modules/lazy-loading. On the subsequent page it says the Firebase modules are in their own bundle/chunk. This is no longer true. It is actually in 4 different chunks.

![screencapture-file-C-code-play-nextjs-next-learn-demo-E2-lazy-loading-modules-next-analyze-client-html-2020-01-29-19_51_17](https://user-images.githubusercontent.com/4006431/73416016-d4db6400-42d0-11ea-8aec-15b244fc6610.png)

Same issue at https://nextjs.org/learn/excel/lazy-loading-components/lets-analyze and https://nextjs.org/learn/excel/lazy-loading-components/analyze-result.

**Comment by chibicode** [comment]
Hi @dhurlburtusa, thank you for reporting! I'll work on a fix.

Note to self - same issue as: https://github.com/zeit/next.js/issues/10282
