### ISSUE TITLE
Confusing Wording on Lazy Loading Modules Tutorial Page

### ISSUE THREAD

**Issue by dhurlburtusa** [zeit/next-site#557]
On https://nextjs.org/learn/excel/lazy-loading-modules/lazy-loading, in the first paragraph after the first code block, it says "This is a pretty decent code ...". What is trying to be conveyed? Size of the imported code? Something else?

If you let me know, I can whip up a PR to fix the wording.

**Comment by lfades** [comment]
@dhurlburtusa Feel free to open a PR, "This is a pretty decent code ..." feels wrong and shouldn't be there.

**Comment by dhurlburtusa** [comment]
@lfades What do you think we should change the following paragraph to?
```
This code is used inside the `getInitialProps` function in each page. This is a pretty decent code and it uses `require` to load the firebase modules.
```
How about
```
This code is used inside the `getInitialProps` function in each page, and it uses `require` to load the firebase modules.
```
?

@chibicode Do you want to take care of this change in your work on #533? Or just deal with the merge (unlikely to be conflict depending on what you plan to change).

**Comment by lfades** [comment]
@dhurlburtusa Your change looks good, feel free to create a PR 😌
