### ISSUE TITLE
Missing attribution for twemoji

### ISSUE THREAD

**Issue by singingwolfboy** [zeit/next-site#562]
This project is currently using graphics from the [Twemoji](https://twemoji.twitter.com/) project in the [feedback component](https://github.com/zeit/next-site/blob/891cbd5fda21b23c88373d5535689dba2c11590a/components/feedback.js#L616), as shown in this screenshot:

<img width="254" alt="screenshot of feedback component" src="https://user-images.githubusercontent.com/132355/73605628-de025480-45a0-11ea-9dba-f6791d8bf440.png">

According to the Twemoji website, the project is licensed as follows:

> Copyright 2020 Twitter, Inc and other contributors
> Code licensed under the MIT License: http://opensource.org/licenses/MIT
> Graphics licensed under CC-BY 4.0: https://creativecommons.org/licenses/by/4.0/

Note that the graphics are licensed under a Creative Commons license that _requires_ attribution. The Twemoji website provides several different options for this attribution:

> As an open source project, attribution is critical from a legal, practical and motivational perspective in our opinion. The graphics are licensed under the CC-BY 4.0 which has a pretty good guide on best practices for attribution.
> 
> However, we consider the guide a bit onerous and as a project, will accept a mention in a project README or an 'About' section or footer on a website. In mobile applications, a common place would be in the Settings/About section (for example, see the mobile Twitter application Settings->About->Legal section). We would consider a mention in the HTML/JS source sufficient also.

I have not found any attribution in this project, so it appears to me that this project is currently in violation of the Creative Commons license. To resolve this issue, this project can either provide attribution, or stop using the Twemoji graphics. Providing attribution is very easy: a line at the bottom of the README saying "This project uses Twemoji" with a link to the Twemoji website should suffice.

Note: even though this project does not currently depend on the [`twemoji` package on npm](https://www.npmjs.com/package/twemoji), it is _still_ using the graphics (hosted on `https://assets.zeit.co/twemoji`). As a result, attribution is still required.

**Comment by lfades** [comment]
@singingwolfboy Thank you for the heads up, attribution will be added to the README 👍
