### ISSUE TITLE
/getInitialProps Doc, responses with 404 page

### ISSUE THREAD

**Issue by ru03** [zeit/next-site#593]
Hi!

If you try to navigate to '/getInitialProps' documentation, a 404 page could not be found is shown.

Link: https://nextjs.org/docs/api-reference/data-fetching/getInitialProps

**Comment by ru03** [comment]
Same issue with next doc links:
- /exportPathMap
- /configuring-onDemandEntries

I would like to help but I'm a noob with NextJs. I was reading the documentation when I discovered that 404.

**Comment by lfades** [comment]
Thank you for the report, this is my priority right now!

**Comment by lfades** [comment]
Rolled back latest PR until it's fixed
