### ISSUE TITLE
Typo in an image

### ISSUE THREAD

**Issue by rojasleon** [zeit/next-site#639]
Hi there!
There's a small typo in a image in the Next.js tutorial.
It says`reqequest` instead of `request`
Here's the link to the image [Static Generation Image](https://github.com/zeit/next-site/blob/master/public/static/images/learn/data-fetching/static-generation.png).

Thank you so much for the new update!  😊
![static_generation](https://user-images.githubusercontent.com/27437337/79798379-86ad8e00-831e-11ea-8a6f-e5c7aeb3dab2.png)

**Comment by chibicode** [comment]
@rojasleon great catch! Fixing this now.
