### ISSUE TITLE
Homepage display broken on iPhone5/SE

### ISSUE THREAD

**Issue by abhishekjakhar** [zeit/next-site#696]
## Description

The homepage of nextjs is broken on iPhone 5/SE, basically on all sizes below 330 pixels.

### Steps to reproduce

1. Go to the home page of https://nextjs.org/ on iPhone 5/SE
2. Scroll down to the **Who’s Using Next.js** section
3. You will see the images are moving out of the normal display

### Expected result

1. Changed the flex rule from **flex: 0 0 50%** to **flex: 0 0 100%** for the container of figure element.
2. I have given width of **100%** to the container of image 

<img width="400" alt="expected-result" src="https://user-images.githubusercontent.com/19193724/81831722-5347d300-955b-11ea-8290-15278c69cbab.png">

### Actual result

Fixed width of 330 pixel is given to container of image

<img width="400" alt="actual-result" src="https://user-images.githubusercontent.com/19193724/81831730-56db5a00-955b-11ea-85e8-29cc04571835.png">

**Comment by timneutkens** [comment]
Feel free to send a PR 💯Great investigating 🕵️

**Comment by abhishekjakhar** [comment]
Okay, I will raise the PR

**Comment by abhishekjakhar** [comment]
@timneutkens I have sent a PR

**Comment by timneutkens** [comment]
Awesome @abhishekjakhar 💯
