### ISSUE TITLE
Section for learning resources (books, videos etc)

### ISSUE THREAD

**Issue by timneutkens** [zeit/next-site#79]
For example:
- https://leanpub.com/hands-on-nextjs by @christiannwamba
- https://www.amazon.com/-/e/B07JHWWFJ7 by @kirill-konshin
- https://advancedreact.com/ by @wesbos

There are also great youtube videos about Next.js.

**Comment by kirill-konshin** [comment]
I can do a PR, if you want.

**Comment by kirill-konshin** [comment]
Correct URL for the book is this one btw https://www.amazon.com/gp/product/B07FNX8NM5/ or on publisher website https://www.packtpub.com/web-development/nextjs-quick-start-guide

**Comment by timneutkens** [comment]
We'll first discuss this internally and @quietshu will make a design 👍

**Comment by timneutkens** [comment]
Another one for the list is @remy's course on Next.js, I forgot to add it yesterday

**Comment by remy** [comment]
And by magic, @remy's course URL appeared! https://next.training.leftlogic.com (use "zeit" for a special discount 🥰)

**Comment by timneutkens** [comment]
🧙‍♂️👍

**Comment by timneutkens** [comment]
Going to close this for now. Might be tackled later.
