### ISSUE TITLE
Components folder

### ISSUE THREAD

**Issue by gringogidget** [zeit/next-site#81]
It isn't clear in the Next.js tutorial that the Components folder should be at the same level as the Pages folder. I'm a super newb at this, but thought I might add a note as it took me quite a while to figure this out :) 

Maybe for _absolute_ new people it would also be worth it to mention that you need to install Node and Brew from their websites and not the console. 

Enjoying the tutorials, otherwise. 🥰

**Comment by quietshu** [comment]
Nope, the `components` folder is not required at all. Actually you could put it anywhere with any name. 

Also thanks for the suggestion! 😃

**Comment by hollowmyth** [comment]
Actually on the "Using Shared Components" section of the tutorial, the git checkout points to the navigate-between-pages branch, but I think it should point to using-shared-components branch. That's the branch that has the components folder in the root.
