### ISSUE TITLE
Link to docs repo?

### ISSUE THREAD

**Issue by kaycebasques** [zeit/next-site#88]
# Feature request

## Is your feature request related to a problem? Please describe.

I was going to propose a change to your Getting Started tutorial, but can't seem to find your docs repo.

## Describe the solution you'd like

Put an "edit this page" button on each docs page.

## Describe alternatives you've considered

Put a link to your docs repo somewhere in the footer.

**Comment by timneutkens** [comment]
I've combined all repos
