### ISSUE TITLE
Showcase: Freezyboy

### ISSUE THREAD

**Issue by pozylon** [zeit/next-site#94]
- Name of company: Freezyboy
- Url: https://freezyboy.com
- Testimonial about Next.js (optional): Hybrid Landing Page + Storefront for a Swiss startup called Freezyboy. No Redux, no router, no config hell, just plain Next + Apollo GraphQL. It was an amazing journey to build the app that way.

**Comment by timneutkens** [comment]
Feel free to send a PR! instructions can be found here: https://github.com/zeit/next-site#adding-a-showcase
